name: Keep Script Running
on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run script
        run: ./soul.py
